# Generated by Django 2.2.13 on 2020-08-05 15:21

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0016_version_mutation_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('known_format', models.BooleanField(help_text='If this file is of a recognized format')),
                ('columns', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('nrows', models.PositiveIntegerField(default=0, help_text='The number of rows in the file')),
                ('ncols', models.PositiveIntegerField(default=0, help_text='The number of columns in the file')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Time the version was created')),
                ('creator', models.ForeignKey(blank=True, help_text='The user who created this analysis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to=settings.AUTH_USER_MODEL)),
                ('version', models.OneToOneField(help_text='The file that this analsis belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='files.Version')),
            ],
            options={
                'permissions': [('list_all_analysis', 'Can list all analyses'), ('view_my_analysis', 'Can view all analyses in studies user is a member of'), ('add_my_study_analysis', 'Can add analyses to studies the user is a member of'), ('change_my_study_analysis', 'Can change analyses in studies the user is a member of')],
            },
        ),
    ]
