# Generated by Django 2.2.13 on 2020-08-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='error_message',
            field=models.TextField(help_text='Error message resulting from a failed attempt to analyze a version', null=True),
        ),
    ]
