# Generated by Django 2.2.13 on 2020-08-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0002_analysis_error_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'permissions': [('list_all_analysis', 'Can list all analyses'), ('view_my_study_analysis', 'Can view all analyses in studies user is a member of'), ('add_my_study_analysis', 'Can add analyses to studies the user is a member of'), ('change_my_study_analysis', 'Can change analyses in studies the user is a member of')]},
        ),
    ]
