FILE_TYPES = {
    "OTH": {"name": "Other", "required_columns": [], "template": None},
    "SHM": {
        "name": "Shipping Manifest",
        "required_columns": [],
        "template": None,
    },
    "CLN": {"name": "Clinical Data", "required_columns": [], "template": None},
    "DBG": {
        "name": "dbGaP Submission File",
        "required_columns": [],
        "template": None,
    },
    "FAM": {
        "name": "Familial Relationships",
        "required_columns": [],
        "template": None,
    },
    "SEQ": {
        "name": "Sequencing Manifest",
        "required_columns": [
            "Aliquot ID",
            "Source Sequencing Filepath",
            "Sequencing Center",
            "Experiment Name",
            "Experiment Strategy",
            "Experiment Date",
            "Instrument Model",
            "Library Name",
            "Library Platform",
            "Library Strand",
            "Library Selection",
            "Library Prep",
            "Is Paired End",
            "Reference Genome",
            "Analyte Type",
            "Max Insert Size",
            "Mean Insert Size",
            "Mean Depth",
            "Total Reads",
            "Mean Read Length"
        ],
        "template": "sequencing_manifest_config.py",
    },
    "S3S": {
        "name": "S3 Scrapes",
        "required_columns": ["Bucket", "Key", "Size", "ETag"],
        "template": "s3_scrape_config.py",
    },
    "PDA": {
        "name": "Participant Demographic and Administrative File",
        "required_columns": [
            "Family ID",
            "Participant ID",
            "dbGaP Consent Code",
            "Clinical Sex",
            "Gender Identity",
            "Race",
            "Ethnicity",
            "Age at Study Enrollment Value",
            "Age at Study Enrollment Units",
            "Affected Status",
            "Proband",
            "Species"
        ],
        "template": "participant_config.py",
    },
    "PTD": {
        "name": "Participant Diseases",
        "required_columns": [
            "Participant ID",
            "Age at Onset Value",
            "Age at Onset Units",
            "Age at Abatement Value",
            "Age at Abatement Units",
            "Condition Name",
            "Condition MONDO Code",
            "Verification Status",
            "Body Site Name",
            "Body Site UBERON Code",
            "Category",  # Will be deprecated
            "Spatial Descriptor",  # Will be deprecated
        ],
        "template": "participant_diseases_config.py",
    },
    "PTP": {
        "name": "Participant Phenotypes",
        "required_columns": [
            "Participant ID",
            "Age at Onset Value",
            "Age at Onset Units",
            "Age at Abatement Value",
            "Age at Abatement Units",
            "Condition Name",
            "Condition HPO Code",
            "Verification Status",
            "Body Site Name",
            "Body Site UBERON Code"
        ],
        "template": "participant_phenotypes_config.py",
    },
    "PTO": {
        "name": "Participant Outcomes",
        "required_columns": [
            "Participant ID",
            "Vital Status",
            "Age at Status Value",
            "Age at Status Units",
            "Disease Related",
        ],
        "template": "participant_outcomes_config.py",
    },
    "POB": {
        "name": "Participant Observations",
        "required_columns": [
            "Participant ID",
            "Age at Observation Value",
            "Age at Observation Units",
            "Observation Name",
            "Observation Ontology Ontobee URI",
            "Observation Code",
            "Category",
            "Interpretation",
            "Status",
            "Body Site Name",
            "Body Site UBERON Code"
        ],
        "template": "participant_observations_config.py",
    },
    "FTR": {
        "name": "Family Trio",
        "required_columns": [
            "Participant ID",
            "Mother Participant ID",
            "Father Participant ID",
        ],
        "template": "family_trio_config.py",
    },
    "FCM": {
        "name": "Complex Family",
        "required_columns": [
            "Source Participant ID",
            "Target Participant ID",
            "Family Relationship",
        ],
        "template": "complex_family_config.py",
    },
    "GWO": {
        "name": "Genomic Workflow Output Manifest",
        "required_columns": [
            "Cavatica ID",
            "Cavatica Task ID",
            "KF Biospecimen ID",
            "KF Participant ID",
            "KF Family ID",
            "Filepath",
            "Data Type",
            "Workflow Type",
            "Source Read",
        ],
        "template": "genomic_workflow_output_manifest_config.py",
    },
    "SAM": {
        "name": "Sample Manifest",
        "required_columns": [
            "Participant ID",
            "Sample ID",
            "Aliquot ID",
            "Consent Group",
            "Tissue Type",
            "Composition",
            "Body Site Name",
            "Body Site UBERON Code",
            "Age at Collection Value",
            "Age at Collection Units",
            "Descriptor",
            "Method of Sample Procurement",
            "Volume",
            "Volume Units",
            "Concentration",
            "Concentration Units",
            "Consent Short Name",  # Will be deprecated
        ],
        "template": "sample_manifest_config.py",
    },
}
