version: '3.4'

services:
  web:
    build:
      context: .
      target: dev
    environment:
      - PG_NAME=study-creator
      - PG_USER=study-creator
      - PG_PASS=password
      - PG_HOST=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-creator.settings.testing}
      - DEFAULT_FILE_STORAGE=django.core.files.storage.FileSystemStorage
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      # Options are: DATASERVICE, url of dataservice, or FAKE
      - PRELOAD_DATA=${PRELOAD_DATA:-FAKE}
      - CAVATICA_HARMONIZATION_TOKEN
      - CAVATICA_DELIVERY_TOKEN
      - CAVATICA_USER_ACCESS_PROJECT
      - FEAT_CAVATICA_COPY_USERS=False
      - USER_ROLES
      - USER_GROUPS
    volumes:
      - .:/app
    ports:
      - '5002:8080'
    depends_on:
      - postgres
      - redis
  worker:
    build:
      context: .
      target: dev
    command: '/app/bin/dev_worker.sh'
    volumes:
      - ./:/app/
    environment:
      - PG_NAME=study-creator
      - PG_USER=study-creator
      - PG_PASS=password
      - PG_HOST=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-creator.settings.testing}
    depends_on:
      - postgres
      - redis
      - web
  postgres:
    image: postgres:11.1
    environment:
      - POSTGRES_DB=study-creator
      - POSTGRES_USER=study-creator
      - POSTGRES_PASSWORD=password
  redis:
    image: redis:latest
networks:
  default:
    external:
      name: kf-data-stack
