version: '3.4'

services:
  web:
    build:
      context: .
      target: dev
    environment:
      - PG_NAME=study-creator
      - PG_USER=study-creator
      - PG_PASS=password
      - PG_HOST=postgres
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-creator.settings.testing}
      - DEFAULT_FILE_STORAGE=django.core.files.storage.FileSystemStorage
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      # Options are: DATASERVICE, url of dataservice, or FAKE
      - PRELOAD_DATA=${PRELOAD_DATA:-FAKE}
      - CAVATICA_HARMONIZATION_TOKEN
      - CAVATICA_DELIVERY_TOKEN
      - CAVATICA_USER_ACCESS_PROJECT
      - FEAT_CAVATICA_COPY_USERS=False
    volumes:
      - .:/app
    ports:
      - '8080:8080'
  postgres:
    image: postgres:11.1
    environment:
      - POSTGRES_DB=study-creator
      - POSTGRES_USER=study-creator
      - POSTGRES_PASSWORD=password
networks:
  default:
    external:
      name: kf-data-stack
