# Generated by Django 2.1.11 on 2020-05-22 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('studies', '0016_add_phenotype_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralToken',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(help_text='The email that the token link will be sent to', max_length=254)),
                ('claimed', models.BooleanField(default=False, help_text='If the token has been used')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Time the referral token was created')),
                ('claimed_by', models.ForeignKey(blank=True, help_text='The user who claims the token', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_tokens_claimed_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created the token', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_tokens_created_by', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The role the user will assume in these studies', related_name='referral_tokens', related_query_name='referral_tokens', to='auth.Group')),
                ('studies', models.ManyToManyField(help_text='List of studies that the user will be added to', related_name='referral_tokens', to='studies.Study')),
            ],
            options={
                'permissions': [('list_all_referraltoken', 'Can view all referral tokens')],
            },
        ),
    ]
