# Generated by Django 2.2.20 on 2021-05-11 16:00

from django.db import migrations, models
import django.db.models.deletion


def set_default_org(apps, schema_editor):
    """
    Add the default organization to each existing referral token
    """
    Organization = apps.get_model("organizations", "Organization")
    ReferralToken = apps.get_model("referral_tokens", "ReferralToken")
    org = Organization.objects.filter(name="Default Organization").first()

    for referral_token in ReferralToken.objects.all().iterator():
        referral_token.organization_id = org.pk
        referral_token.save()


def delete_default_org(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "__first__"),
        ("referral_tokens", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="referraltoken",
            name="organization",
            field=models.ForeignKey(
                help_text="The organization the user will be added to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral_tokens",
                to="organizations.Organization",
            ),
        ),
        migrations.RunPython(set_default_org, delete_default_org),
        migrations.AlterField(
            model_name="referraltoken",
            name="organization",
            field=models.ForeignKey(
                help_text="The organization the user will be added to",
                null=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral_tokens",
                to="organizations.Organization",
            ),
        ),
    ]
