# Generated by Django 2.1.7 on 2019-06-06 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0003_auto_20190226_2048'),
        ('files', '0011_add_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Time the event was created')),
                ('event_type', models.CharField(choices=[('SF_CRE', 'Study File Created'), ('SF_UPD', 'Study File Updated'), ('SF_DEL', 'Study File Deleted'), ('SV_CRE', 'File Version Created'), ('SV_UPD', 'File Version Updated'), ('OTH', 'Other')], default='OTH', max_length=6)),
                ('description', models.TextField(blank=True, default='', help_text='Description of the event', max_length=1000)),
                ('file', models.ForeignKey(blank=True, help_text='File related to this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='files.File')),
                ('study', models.ForeignKey(blank=True, help_text='Study related to this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='studies.Study')),
                ('user', models.ForeignKey(blank=True, help_text='User related to this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(blank=True, help_text='Version related to this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='files.Version')),
            ],
        ),
    ]
