# Generated by Django 2.1.11 on 2020-04-08 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_collaborator_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('view_my_event', 'Can view all events in studies user is a member of')]},
        ),
    ]
