# Generated by Django 2.2.13 on 2021-03-30 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest_runs', '0002_refactor_to_ingest_process'),
        ('events', '0015_add_ingest_run_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ingest_run',
            field=models.ForeignKey(blank=True, help_text='Ingest Run related to this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='ingest_runs.IngestRun'),
        ),
    ]
