# Generated by Django 2.2.26 on 2022-01-27 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # Need to force load the referral_tokens app by making dependency on
        # latest migration. If we don't do this the migration fails bc it
        # cannot find the related model, referral_tokens.ReferralToken
        # https://stackoverflow.com/questions/33496333/valueerror-related-model-uapp-model-cannot-be-resolved
        ('referral_tokens', '__latest__'),
        ('events', '0021_add_template_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='referral_token',
            field=models.ForeignKey(blank=True, help_text='Referral token related to this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='referral_tokens.ReferralToken'),
        ),
    ]
