# Generated by Django 2.2.13 on 2020-12-16 19:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when the banner was created', null=True)),
                ('enabled', models.BooleanField(default=False, help_text='Whether to display the banner or not')),
                ('start_date', models.DateTimeField(default=datetime.datetime.now, help_text='When to start displaying the banner', null=True)),
                ('end_date', models.DateTimeField(default=datetime.datetime.now, help_text='When to stop displaying the banner', null=True)),
                ('message', models.TextField(help_text='The message content for the banner', max_length=1000)),
                ('url', models.URLField(blank=True, help_text="A URL that may be included in the Banner's message as an HTML <a> element, pointing to additional information about message.", null=True)),
                ('url_label', models.CharField(blank=True, help_text='A text label meant to be used as a part of the <a> element containing the Banner url.', max_length=200, null=True)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Warning'), ('ERROR', 'Error')], default='INFO', help_text='The severity of the message', max_length=10)),
                ('creator', models.ForeignKey(blank=True, help_text='The user who submitted this ingest run', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('list_all_banner', 'Show all banner')],
            },
        ),
    ]
