# Generated by Django 2.2.13 on 2020-11-02 14:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseEvent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('info', 'info'), ('warning', 'warning'), ('error', 'error')], default='info', help_text='The type of event', max_length=20)),
                ('message', models.CharField(help_text='The message describing the event', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time the event was created')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='releases.Release')),
                ('release_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='releases.ReleaseService')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='releases.ReleaseTask')),
            ],
            options={
                'permissions': [('list_all_releaseevent', 'Show all release events')],
                'get_latest_by': 'created_at',
            },
        ),
    ]
