# Generated by Django 2.2.13 on 2020-11-05 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_move_jobs'),
        ('releases', '0002_add_release_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='job_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='jobs.JobLog'),
        ),
        migrations.AlterField(
            model_name='releasetask',
            name='job_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='jobs.JobLog'),
        ),
    ]
