# Generated by Django 2.2.24 on 2021-10-13 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0004_remove_delete_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='ended_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Date ended', null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date created'),
        ),
    ]
