# Generated by Django 2.2.20 on 2021-04-29 01:19

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the organization', max_length=1024)),
                ('description', models.TextField(help_text='Description of the organization', null=True)),
                ('email', models.EmailField(help_text='Email address for the organization', max_length=254, null=True)),
                ('website', models.URLField(help_text="Url for the organization's website", null=True)),
                ('image', models.URLField(help_text="Url for the organization's display image", null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Time the organization was created')),
                ('members', models.ManyToManyField(help_text='Users that belong to this organization', related_name='organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('list_all_organization', 'Can list all organizations'), ('view_my_organization', 'Can list organizations that the user belongs to')],
            },
        ),
    ]
