# Generated by Django 2.2.24 on 2021-12-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='dewrangle_id',
            field=models.CharField(
                help_text='Unique identifier of the org in Dewrangle',
                blank=True, max_length=1024, null=True
            ),
        ),
    ]
