# Generated by Django 2.2.13 on 2020-09-17 16:29

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0020_version_extract_config_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Time the validiation was created')),
                ('creator', models.ForeignKey(blank=True, help_text='The user who created this validation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations', to=settings.AUTH_USER_MODEL)),
                ('versions', models.ManyToManyField(help_text='Versions used as input to the validation', related_name='validations', to='files.Version')),
            ],
            options={
                'permissions': [('list_all_validation', 'Can list all validations'), ('view_my_study_validation', 'Can view all validations in studies user is a member of'), ('add_my_study_validation', 'Can create validations for documents in studies the user is a member of')],
            },
        ),
    ]
