version: 2
jobs:
  build:
    docker:
      - image: python:3
        environment:
          AWS_ACCESS_KEY_ID: foobar_secret
          AWS_SECRET_ACCESS_KEY: foobar_secret
    steps:
      - checkout:
          path: ~/workdir
      - run:
          name: Install dependencies
          working_directory: ~/workdir
          command: |
            pip install -r requirements.txt
            pip install -r dev-requirements.txt
      - run:
          name: Run code tests
          working_directory: ~/workdir
          command: |
            pytest
      - run:
          name: Lint documentation
          working_directory: ~/workdir
          command: |
            doc8 docs
      - run:
          name: Build docs site
          working_directory: ~/workdir
          command: |
            sphinx-build -W docs staged
      - run:
          name: Deploy if master branch
          working_directory: ~/workdir
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                touch .nojekyll
                git config --global user.email "dankolbman@gmail.com"
                git config --global user.name "Dan Kolbman"
                mv staged/ ../
                git checkout -b gh-pages
                git pull origin gh-pages
                mv ../staged/* ./
                git add -A .
                git commit --allow-empty -m ":recycle: Update docs site"
                git push -q https://${GITHUB_TOKEN}@github.com/kids-first/kf-api-study-creator.git
            fi
