version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    steps:
      - checkout:
          path: ~/workdir
      - run:
          name: Do nothing
          working_directory: ~/workdir
          command: |
            echo "Don't do anything for gh-page"
