version: 2
jobs:
  build:
    working_directory: ~/workdir
    branches:
      ignore:
        - gh-pages
    docker:
      - image: python:3.8
        environment:
          - PG_USER=study-creator
          - PG_PASS=password
          - PG_HOST=localhost
          - REDIS_HOST=localhost
          - DEFAULT_FILE_STORAGE=django.core.files.storage.FileSystemStorage
          - AWS_ACCESS_KEY_ID=foobar_secret
          - AWS_SECRET_ACCESS_KEY=foobar_secret
      - image: circleci/postgres:10.6
        environment:
          - POSTGRES_DB=study-creator
          - POSTGRES_USER=study-creator
          - POSTGRES_PASSWORD=password
      - image: redis:latest
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "dev-requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r dev-requirements.txt
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "dev-requirements.txt" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8/site-packages"
      - run:
          name: Run code tests
          command: |
            pytest
            codecov --token=$CODECOV_TOKEN
      - run:
          name: Lint documentation
          command: |
            doc8 docs
      - run:
          name: Build docs site
          command: |
            sphinx-build -W docs staged
      - run:
          name: Deploy if master branch
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                touch .nojekyll
                git config --global user.email "dankolbman@gmail.com"
                git config --global user.name "Dan Kolbman"
                mv staged/ ../
                git checkout -b gh-pages
                git fetch origin gh-pages
                git reset --hard origin/gh-pages
                rm -r ./*
                mv ../staged/* ./
                git add -A .
                git commit --allow-empty -m ":recycle: Update docs site"
                git push -q https://${GITHUB_TOKEN}@github.com/kids-first/kf-api-study-creator.git
            fi
