# Generated by Django 2.2.13 on 2021-02-23 19:30

import creator.data_reviews.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0022_add_genomic_workflow_output_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataReview",
            fields=[
                (
                    "kf_id",
                    models.CharField(
                        default=creator.data_reviews.models.data_review_id,
                        help_text="Kids First ID assigned to the data review",
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, help_text="UUID used internally"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Time when the data_review was created",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the data review", max_length=256
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of data review",
                        max_length=10000,
                        null=True,
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMField(
                        default="not_started",
                        help_text="The current state of the data review",
                        max_length=50,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who created the data review",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_reviews",
                        to="studies.Study",
                    ),
                ),
                (
                    "versions",
                    models.ManyToManyField(
                        help_text="kf_ids of the file versions in this data review",
                        related_name="data_reviews",
                        to="files.Version",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("list_all_datareview", "Show all data_reviews")
                ],
            },
        ),
    ]
