# Generated by Django 2.2.13 on 2021-04-07 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datareview',
            options={'permissions': [('list_all_datareview', 'Show all data_reviews'), ('add_my_study_datareview', 'Can add data reviews in studies that the user is a member of'), ('change_my_study_datareview', 'Can change data reviews in studies that the user is a member of'), ('delete_my_study_datareview', 'Can delete data reviews in studies that the user is a member of'), ('view_my_study_datareview', 'Can view all data reviews in studies that the user is a member of')]},
        ),
    ]
