# Generated by Django 2.1.7 on 2019-06-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_auto_20190226_2048'),
        ('creator', '0004_add_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='study_subscriptions',
            field=models.ManyToManyField(help_text='Tracks studies that user is following', to='studies.Study'),
        ),
    ]
