# Generated by Django 2.1.7 on 2019-06-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0005_add_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slack_member_id',
            field=models.CharField(blank=True, default='', help_text="The user's slack member id", max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='slack_notify',
            field=models.BooleanField(default=False, help_text='Whether the user has enabled slack notifications'),
        ),
    ]
