# Generated by Django 2.1.11 on 2020-02-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0008_nonunique_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('name', models.CharField(help_text='The name of the scheduled job', max_length=400, primary_key=True, serialize=False)),
                ('scheduler', models.CharField(help_text='The scheduler the Job will run on', max_length=400)),
                ('description', models.TextField(help_text="Description of the Job's role", null=True)),
                ('active', models.BooleanField(default=True, help_text='If the Job is active')),
                ('failing', models.BooleanField(default=False, help_text='If the Job is failing')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Time the Job was created')),
                ('last_run', models.DateTimeField(help_text='Time of last run', null=True)),
                ('last_error', models.TextField(help_text='Error message from last failure', null=True)),
            ],
        ),
    ]
