# Generated by Django 2.1.11 on 2020-03-18 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0009_add_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('list_all_user', 'Can list all users')]},
        ),
    ]
