# Generated by Django 2.1.11 on 2020-04-08 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0010_list_all_users_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'permissions': [('view_settings', 'Can view settings'), ('view_queue', 'Can view queues')]},
        ),
    ]
