# Generated by Django 2.2.13 on 2020-09-23 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0011_add_custom_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
