# Generated by Django 2.2.13 on 2021-03-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0012_move_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ego_groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ego_roles',
        ),
    ]
