# Generated by Django 2.2.24 on 2021-08-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateversion',
            name='description',
            field=models.TextField(blank=True, help_text='Description of changes in this template version', max_length=10000, null=True),
        ),
    ]
