# Generated by Django 2.2.24 on 2021-12-20 01:51

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now,
                 help_text='When the expected file was created', null=True)),
                ('file_location', models.CharField(
                    help_text='The original name of the uploaded file', max_length=200)),
                ('hash', models.CharField(
                    help_text='The hash digest of file before upload', max_length=1024)),
                ('hash_algorithm', models.CharField(
                    help_text='The name of the hash algorithm used to compute the file hash', max_length=500)),
                ('size', models.BigIntegerField(help_text='Size of the uploaded file in bytes', validators=[
                 django.core.validators.MinValueValidator(0, 'File size must be a positive number')])),
                ('custom_fields', django.contrib.postgres.fields.jsonb.JSONField(
                    default=dict, help_text='Additional fields in the file upload manifest that need to be captured')),
                ('audit_state', django_fsm.FSMField(default='not_submitted',
                 help_text='The state of the expected file in the submission process toDewrangle', max_length=50)),
                ('study', models.ForeignKey(help_text='id of the study whose cloud storage this file was uploaded to',
                 on_delete=django.db.models.deletion.CASCADE, related_name='expected_files', to='studies.Study')),
            ],
            options={
                'permissions': [('list_all_expectedfiles', 'Show all expected_files')],
            },
        ),
        migrations.AddConstraint(
            model_name='expectedfile',
            constraint=models.UniqueConstraint(
                fields=('file_location', 'study_id'), name='unique_expected_file'),
        ),
    ]
