# Generated by Django 2.2.24 on 2022-01-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_analyses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileaudit',
            name='expected_url',
            field=models.URLField(blank=True, help_text='Url of the file in cloud storage', max_length=1000, null=True),
        ),
    ]
