# Generated by Django 2.1.7 on 2019-02-18 20:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileEssence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Description of the file', max_length=1000)),
                ('study', models.ForeignKey(help_text='The study this file belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='studies.Study')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The s3 key where this object is located', max_length=1023, validators=[django.core.validators.RegexValidator("[A-Za-z0-9 !\\-\\_\\.\\*\\'\\(\\)\\/]+")])),
                ('version_id', models.CharField(help_text='The s3 version id of this object', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time the object was created')),
                ('root_file', models.ForeignKey(help_text='The file that this version object belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='files.FileEssence')),
            ],
        ),
    ]
