# Generated by Django 2.1.7 on 2019-02-16 16:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileEssence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='studies.Study')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=63, validators=[django.core.validators.RegexValidator('(?=^.{3,63}$)(?!^(\\d+\\.)+\\d+$)(^(([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])\\.)*([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])$)')])),
                ('key', models.CharField(max_length=1023, validators=[django.core.validators.RegexValidator("[A-Za-z0-9 !\\-\\_\\.\\*\\'\\(\\)\\/]+")])),
                ('version_id', models.CharField(max_length=32)),
                ('root_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='files.FileEssence')),
            ],
        ),
    ]
