# Generated by Django 2.1.7 on 2019-03-05 01:07

import creator.fields
import creator.files.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0003_auto_20190226_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('kf_id', creator.fields.KFIDField(default=creator.files.models.file_id, editable=False, max_length=11, primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Description of the file', max_length=1000)),
                ('file_type', models.CharField(choices=[('SEQ', 'Sequencing Manifest'), ('SHM', 'Shipping Manifest'), ('CLN', 'Clinical Data'), ('FAM', 'Familial Relationships')], max_length=3)),
                ('study', models.ForeignKey(help_text='The study this file belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='studies.Study')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('kf_id', creator.fields.KFIDField(default=creator.files.models.object_id, editable=False, max_length=11, primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('key', models.FileField(help_text='Field to track the storage location of the object', max_length=512, upload_to=creator.files.models._get_upload_directory)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Time the object was created')),
                ('size', models.BigIntegerField(help_text='Size of the object in bytes', validators=[django.core.validators.MinValueValidator(0, 'File size must be a positive number')])),
                ('root_file', models.ForeignKey(help_text='The file that this version object belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='files.File')),
            ],
        ),
    ]
