# Generated by Django 2.1.7 on 2019-02-25 19:37

import creator.files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='key',
            field=models.FileField(help_text='Field to track the storage location of the object', max_length=512, upload_to=creator.files.models._get_upload_directory),
        ),
    ]
