# Generated by Django 2.1.7 on 2019-03-26 14:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import functools
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=functools.partial(secrets.token_urlsafe, *(20,), **{}), editable=False, help_text='The value of the token', max_length=27)),
                ('claimed', models.BooleanField(default=False, help_text='Whether the token has been claimed for a download')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Time the token was created')),
                ('root_object', models.ForeignKey(help_text='The object that this token was generated for', on_delete=django.db.models.deletion.CASCADE, related_name='object', to='files.Object')),
            ],
        ),
    ]
