# Generated by Django 2.1.7 on 2019-02-19 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Time the object was created'),
        ),
    ]
