# Generated by Django 2.1.7 on 2019-03-29 17:54

from django.db import migrations, models
import django.utils.timezone
import functools
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_other_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevDownloadToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name describing the token', max_length=100)),
                ('token', models.CharField(default=functools.partial(secrets.token_urlsafe, *(20,), **{}), editable=False, help_text='The value of the token', max_length=27)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Time the token was created')),
            ],
        ),
    ]
