# Generated by Django 2.1.7 on 2019-04-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_dev_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devdownloadtoken',
            name='name',
            field=models.CharField(editable=False, help_text='Name describing the token', max_length=100, unique=True),
        ),
    ]
