# Generated by Django 2.1.7 on 2019-05-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_dev_tokens_unique_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.TextField(help_text='Description of the file', max_length=10000),
        ),
    ]
