# Generated by Django 2.1.7 on 2019-05-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_increase_description_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Object',
            new_name='Version',
        ),
    ]
