# Generated by Django 2.1.7 on 2019-05-22 17:36

import creator.fields
import creator.files.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('files', '0007_rename_objects_to_versions'), ('files', '0008_update_version_foreign_keys'), ('files', '0009_update_version_descriptions')]

    dependencies = [
        ('files', '0006_increase_description_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Object',
            new_name='Version',
        ),
        migrations.RenameField(
            model_name='downloadtoken',
            old_name='root_object',
            new_name='root_version',
        ),
        migrations.AlterField(
            model_name='version',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Time the version was created'),
        ),
        migrations.AlterField(
            model_name='version',
            name='key',
            field=models.FileField(help_text='Field to track the storage location of the version', max_length=512, upload_to=creator.files.models._get_upload_directory),
        ),
        migrations.AlterField(
            model_name='version',
            name='kf_id',
            field=creator.fields.KFIDField(default=creator.files.models.version_id, editable=False, max_length=11, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='root_file',
            field=models.ForeignKey(help_text='The file that this version version belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='files.File'),
        ),
        migrations.AlterField(
            model_name='version',
            name='size',
            field=models.BigIntegerField(help_text='Size of the version in bytes', validators=[django.core.validators.MinValueValidator(0, 'File size must be a positive number')]),
        ),
        migrations.AlterField(
            model_name='downloadtoken',
            name='root_version',
            field=models.ForeignKey(help_text='The version that this token was generated for', on_delete=django.db.models.deletion.CASCADE, related_name='version', to='files.Version'),
        ),
    ]
