# Generated by Django 2.1.7 on 2019-05-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_rename_objects_to_versions_squashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='description',
            field=models.TextField(default='', help_text='Description of changes introduced to the file by this version', max_length=10000),
            preserve_default=False,
        ),
    ]
