# Generated by Django 2.1.7 on 2019-05-22 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_update_version_foreign_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadtoken',
            name='root_version',
            field=models.ForeignKey(help_text='The version that this token was generated for', on_delete=django.db.models.deletion.CASCADE, related_name='version', to='files.Version'),
        ),
    ]
