# Generated by Django 2.1.7 on 2019-05-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_add_version_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='state',
            field=models.CharField(choices=[('PEN', 'Pending Review'), ('APP', 'Approved'), ('CHN', 'Changes Needed'), ('PRC', 'Processed')], default='PEN', help_text='The current state of this version', max_length=3),
        ),
    ]
