# Generated by Django 2.1.7 on 2019-05-28 14:18

from django.db import migrations, models


def name_from_file(apps, schema_editor):
    """
    We will populate any existing versions with the name of the parent file
    """
    Version = apps.get_model('files', 'Version')
    for version in Version.objects.all():
        version.file_name = version.root_file.name
        version.save()


class Migration(migrations.Migration):

    replaces = [('files', '0010_add_version_file_name'), ('files', '0011_populate_version_file_name')]

    dependencies = [
        ('files', '0009_add_version_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='file_name',
            field=models.CharField(default='', help_text="The name of the version's file as it was originally uploaded", max_length=1000),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=name_from_file,
        ),
    ]
