# Generated by Django 2.1.7 on 2019-05-31 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0010_version_file_names_squashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='The user who originally created this File', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='version',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='The user who originally created this Version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to=settings.AUTH_USER_MODEL),
        ),
    ]
