# Generated by Django 2.1.7 on 2019-06-09 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0011_add_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='devdownloadtoken',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='The user who originally created this token', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
