# Generated by Django 2.1.11 on 2020-02-25 20:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_add_token_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, help_text='Tags to group the files by', size=None),
        ),
    ]
