# Generated by Django 2.1.11 on 2020-04-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_file_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('OTH', 'Other'), ('SEQ', 'Sequencing Manifest'), ('SHM', 'Shipping Manifest'), ('CLN', 'Clinical Data'), ('DBG', 'dbGaP Submission File'), ('FAM', 'Familial Relationships')], default='OTH', max_length=3),
        ),
    ]
