# Generated by Django 2.1.11 on 2020-04-08 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_add_dbGaP_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devdownloadtoken',
            options={'permissions': [('list_all_version', 'Can list all versions')]},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'permissions': [('list_all_file', 'Can list all files'), ('view_my_file', 'Can view all files in studies user is a member of'), ('add_my_study_file', 'Can add files to studies the user is a member of'), ('change_my_study_file', 'Can change files in studies the user is a member of')]},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'permissions': [('view_my_version', 'Can view all versions in studies user is a member of'), ('add_my_study_version', 'Can add versions to studies the user is a member of'), ('change_my_study_version', 'Can change versions in studies the user is a member of')]},
        ),
    ]
