# Generated by Django 2.2.13 on 2020-07-15 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0015_add_custom_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'permissions': [('view_my_version', 'Can view all versions in studies user is a member of'), ('add_my_study_version', 'Can add versions to studies the user is a member of'), ('change_version_meta', 'Can change any version meta'), ('change_version_status', 'Can change any version status'), ('change_my_version_meta', 'Can change version meta in studies the user is a member of'), ('change_my_version_status', 'Can change version status in studies the user is a member of')]},
        ),
    ]
