# Generated by Django 2.2.13 on 2020-08-12 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0016_version_mutation_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='description',
            field=models.TextField(help_text='Description of changes introduced to the file by this version', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='root_file',
            field=models.ForeignKey(help_text='The file that this version belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='files.File'),
        ),
    ]
