# Generated by Django 2.2.13 on 2020-08-12 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0021_add_study_to_version'),
        ('files', '0017_make_fields_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='study',
            field=models.ForeignKey(help_text='The study that this version belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='studies.Study'),
        ),
    ]
