# Generated by Django 2.2.13 on 2020-09-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0018_add_study_to_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('OTH', 'Other'), ('SEQ', 'Sequencing Manifest'), ('SHM', 'Shipping Manifest'), ('CLN', 'Clinical Data'), ('DBG', 'dbGaP Submission File'), ('FAM', 'Familial Relationships'), ('S3S', 'S3 Scrape')], default='OTH', max_length=3),
        ),
    ]
