# Generated by Django 2.2.20 on 2021-05-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0022_add_genomic_workflow_output_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('OTH', 'OTH'), ('SHM', 'SHM'), ('CLN', 'CLN'), ('DBG', 'DBG'), ('FAM', 'FAM'), ('S3S', 'S3S'), ('PDA', 'PDA'), ('PTD', 'PTD'), (
                'PTP', 'PTP'), ('GOB', 'GOB'), ('FTR', 'FTR'), ('FCM', 'FCM'),
                ('GWO', 'GWO'), ('BCM', 'BCM'), ('BBM', 'BBM'), ('ALM', 'ALM'), ('SEQ', 'SEQ')], default='OTH', max_length=3),
        ),
    ]
