# Generated by Django 2.2.24 on 2021-06-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0024_set_old_types_to_oth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('OTH', 'OTH'), ('DBG', 'DBG'), ('FAM', 'FAM'), ('S3S', 'S3S'), ('PDA', 'PDA'), ('PTD', 'PTD'), ('PTP', 'PTP'), ('GOB', 'GOB'), ('FTR', 'FTR'), ('FCM', 'FCM'), ('GWO', 'GWO'), ('BCM', 'BCM'), ('BBM', 'BBM'), ('ALM', 'ALM'), ('SEQ', 'SEQ')], default='OTH', max_length=3),
        ),
    ]
