# Generated by Django 2.2.24 on 2021-07-26 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_templates', '0001_initial'),
        ('files', '0025_remove_old_file_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='template_version',
            field=models.ForeignKey(blank=True, help_text='The data template version this file conforms to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='data_templates.TemplateVersion'),
        ),
    ]
