# Generated by Django 2.1.11 on 2020-03-04 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0012_add_buckets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('name', models.CharField(help_text='The name of the bucket in S3', max_length=512, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(help_text='Time the bucket was created')),
                ('deleted', models.BooleanField(default=False, help_text='Whether this bucket has been deleted from S3')),
                ('study', models.ForeignKey(help_text='The study this bucket belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buckets', to='studies.Study')),
            ],
        ),
    ]
