# Generated by Django 2.2.13 on 2020-11-12 21:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0002_add_custom_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(help_text='The date the inventory was generated. Not to be confused with the created_at time which is when it was registered in the database')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when the bucket inventory was created')),
                ('key', models.FileField(help_text='Field to track the storage location of the inventory', max_length=512, upload_to='')),
                ('manifest', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Copy of the manifest.json for the inventory that was saved in s3')),
                ('summary', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Summary analysis of the inventory')),
                ('imported', models.BooleanField(default=False, help_text='Whether this inventory was imported or not')),
                ('bucket', models.ForeignKey(help_text='The bucket this inventory belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='buckets.Bucket')),
            ],
            options={
                'permissions': [('list_all_bucketinventory', 'Show all bucket_inventories')],
            },
        ),
    ]
