# Generated by Django 2.2.13 on 2020-09-23 01:31

import creator.jobs.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('name', models.CharField(help_text='The name of the scheduled job', max_length=400, primary_key=True, serialize=False)),
                ('scheduler', models.CharField(default='default', help_text='The scheduler the Job will run on', max_length=400)),
                ('description', models.TextField(help_text="Description of the Job's role", null=True)),
                ('active', models.BooleanField(default=True, help_text='If the Job is active')),
                ('failing', models.BooleanField(default=False, help_text='If the Job is failing')),
                ('scheduled', models.BooleanField(default=False, help_text='If the Job is a recurring scheduled task')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Time the Job was created')),
                ('last_run', models.DateTimeField(help_text='Time of last run', null=True)),
                ('last_error', models.TextField(help_text='Error message from last failure', null=True)),
            ],
            options={
                'permissions': [('list_all_job', 'Can list all jobs'), ('view_settings', 'Can view settings'), ('view_queue', 'Can view queues')],
            },
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error', models.BooleanField(default=False, help_text='If there was an error running the Job')),
                ('log_file', models.FileField(help_text='The location where the log file is stored', max_length=1024, upload_to=creator.jobs.models._get_upload_directory)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time the log was created')),
                ('job', models.ForeignKey(help_text='The Job that this log originated from', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='jobs.Job')),
            ],
            options={
                'permissions': [('list_all_joblog', 'Can list all job logs')],
            },
        ),
    ]
