# Generated by Django 2.2.13 on 2021-01-11 14:48

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_move_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountTask',
            fields=[
                ('kf_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('state', django_fsm.FSMField(default='initialized', help_text='The current state of the task', max_length=50)),
                ('progress', models.IntegerField(default=0, help_text='Optional field representing what percentage of the task has been completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time the task was created')),
                ('job_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='count_service_tasks', to='jobs.JobLog')),
            ],
        ),
    ]
