# Generated by Django 2.2.13 on 2021-03-08 16:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_move_jobs'),
        ('releases', '0004_remove_delete_cascade'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountTask',
            fields=[
                ('kf_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('state', django_fsm.FSMField(default='pending', help_text='The current state of the task', max_length=50)),
                ('progress', models.IntegerField(default=0, help_text='Optional field representing what percentage of the task has been completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time the task was created')),
                ('job_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='count_service_tasks', to='jobs.JobLog')),
                ('release', models.ForeignKey(help_text='The release that this task is running for', on_delete=django.db.models.deletion.CASCADE, related_name='count_tasks', to='releases.Release')),
            ],
        ),
        migrations.CreateModel(
            name='StudySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time the summary was created')),
                ('counts', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Entity counts for the study')),
                ('count_task', models.ForeignKey(help_text='Count Task that created this summary', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summaries', to='count_service.CountTask')),
                ('study', models.ForeignKey(help_text='Study that this summary was generated for', on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='studies.Study')),
            ],
            options={
                'permissions': [('list_all_studysummary', 'Can list all study summaries')],
            },
        ),
    ]
