# Generated by Django 2.1.11 on 2019-08-06 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0005_study_name_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(help_text='The Cavatica project identifier', max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the Cavatica project', max_length=500)),
                ('description', models.TextField(help_text='The description markdown of the Cavatica project')),
                ('url', models.CharField(help_text='The url of the Cavatica project', max_length=500)),
                ('project_type', models.CharField(choices=[('HAR', 'harmonization'), ('DEL', 'delivery')], default='HAR', help_text='The Cavatica project type', max_length=3)),
                ('created_by', models.CharField(help_text='The user who created the Cavatica project', max_length=200)),
                ('created_on', models.DateTimeField(help_text='Time the Cavatica project was created')),
                ('modified_on', models.DateTimeField(help_text='Time of last modification')),
                ('study', models.ForeignKey(help_text='The study this project belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='studies.Study')),
            ],
        ),
    ]
