# Generated by Django 2.1.11 on 2019-08-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_workflow_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='workflow_type',
            field=models.CharField(choices=[('bwa_mem', 'bwa-mem'), ('bwa_mem_bqsr', 'bwa-mem-bqsr'), ('star_2_pass', 'star-2-pass'), ('gatk_haplotypecaller', 'gatk-haplotypecaller'), ('gatk_genotypgvcf', 'gatk-genotypgvcf'), ('gatk_genotypgvcf_vqsr', 'gatk-genotypgvcf-vqsr'), ('strelka2_somatic_mode', 'strelka2-somatic-mode'), ('mutect2_somatic_mode', 'mutect2-somatic-mode'), ('mutect2_tumor_only_mode', 'mutect2-tumor-only-mode'), ('vardict_single_sample_mode', 'vardict-single-sample-mode'), ('vardict_paired_sample_mode', 'vardict-paired-sample-mode'), ('control_freec_somatic_mode', 'control-freec-somatic-mode'), ('control_freec_germline_mode', 'control-freec-germline-mode'), ('stringtie_expression', 'stringtie-expression'), ('manta_somatic', 'manta-somatic'), ('manta_germline', 'manta-germline'), ('lumpy_somatic', 'lumpy-somatic'), ('lumpy_germline', 'lumpy-germline'), ('rsem', 'rsem'), ('kallisto', 'kallisto'), ('star_fusion', 'star-fusion'), ('arriba', 'arriba'), ('peddy', 'peddy')], help_text='The Cavatica project workflow type', max_length=200, null=True),
        ),
    ]
