# Generated by Django 2.1.11 on 2019-08-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_update_workflows'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Whether this project has been deleted from Cavatica'),
        ),
    ]
