# Generated by Django 2.1.11 on 2020-02-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_deleted_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('HAR', 'harmonization'), ('DEL', 'delivery'), ('RES', 'research')], default='HAR', help_text='The Cavatica project type', max_length=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='workflow_type',
            field=models.CharField(help_text='The Cavatica project workflow type', max_length=200, null=True),
        ),
    ]
