# Generated by Django 2.1.11 on 2020-04-09 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200204_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('list_all_project', 'Can list all projects'), ('link_project', 'Can link a project to a study'), ('unlink_project', 'Can unlink a project from a study'), ('sync_project', 'Can sync projects with Cavatica'), ('import_volume', 'Can import a volume to a project'), ('view_my_study_project', 'Can view projects in own studies')]},
        ),
    ]
