# Generated by Django 2.1.7 on 2019-02-19 20:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the batch', max_length=100)),
                ('state', models.CharField(choices=[('CON', 'configuring'), ('MAP', 'mapped'), ('SUB', 'submitted'), ('TRN', 'transformed')], default='CON', max_length=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Time the batch was created')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('kf_id', models.CharField(help_text='The Kids First Identifier', max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the study', max_length=100)),
                ('visible', models.BooleanField(default=True, help_text='If the study is public or not')),
                ('created_at', models.DateTimeField(help_text='Time the study was created', null=True)),
                ('bucket', models.CharField(help_text='The s3 bucket name', max_length=63, validators=[django.core.validators.RegexValidator('(?=^.{3,63}$)(?!^(\\d+\\.)+\\d+$)(^(([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])\\.)*([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])$)')])),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='study',
            field=models.ForeignKey(help_text='The study this batch belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='studies.Study'),
        ),
    ]
