# Generated by Django 2.1.7 on 2019-02-16 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('kf_id', models.CharField(help_text='The Kids First Identifier', max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the study', max_length=100)),
                ('visible', models.BooleanField(default=True, help_text='If the study is public or not')),
                ('created_at', models.DateTimeField(help_text='Time the study was created', null=True)),
                ('bucket', models.CharField(help_text='The s3 bucket name', max_length=63, validators=[django.core.validators.RegexValidator('(?=^.{3,63}$)(?!^(\\d+\\.)+\\d+$)(^(([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])\\.)*([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])$)')])),
            ],
        ),
    ]
