# Generated by Django 2.1.11 on 2019-08-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0005_study_name_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='release_date',
            field=models.DateField(help_text='Scheduled date for release of the study', null=True),
        ),
    ]
