# Generated by Django 2.1.11 on 2019-08-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0006_add_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='description',
            field=models.TextField(default='', help_text='Markdown description of the study'),
        ),
    ]
