# Generated by Django 2.1.11 on 2019-08-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0007_study_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='study',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
