# Generated by Django 2.1.11 on 2020-02-25 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studies', '0010_study_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='collaborators',
            field=models.ManyToManyField(help_text='Users working on this study', to=settings.AUTH_USER_MODEL),
        ),
    ]
