# Generated by Django 2.1.11 on 2020-03-04 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0011_add_collaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='collaborators',
            field=models.ManyToManyField(help_text='Users working on this study', related_name='studies', to=settings.AUTH_USER_MODEL),
        ),
    ]
