# Generated by Django 2.1.11 on 2020-04-08 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0012_add_buckets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'permissions': [('view_my_study', 'Can list studies that the user belongs to'), ('add_collaborator', 'Can add a collaborator to the study'), ('remove_collaborator', 'Can remove a collaborator to the study')]},
        ),
    ]
