# Generated by Django 2.1.11 on 2020-05-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0016_add_phenotype_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='slack_channel',
            field=models.CharField(help_text='The name of the related Slack channel', max_length=80, null=True),
        ),
    ]
