# Generated by Django 2.2.10 on 2020-05-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0017_add_slack_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='slack_notify',
            field=models.BooleanField(default=True, help_text='Whether enabled slack notifications for study updates'),
        ),
    ]
