# Generated by Django 2.1.11 on 2020-06-17 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studies', '0018_add_slack_notify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_on', models.DateTimeField(auto_now_add=True, help_text='Time when user joined the study')),
                ('role', models.CharField(choices=[('RESEARCHER', 'Researcher'), ('INVESTIGATOR', 'Investigator'), ('BIOINFO', 'Bioinformatics Staff'), ('ADMIN', 'Administrative Staff'), ('ANALYST', 'Data Analyst Staff'), ('DEVELOPER', 'Developer')], default='RESEARCHER', help_text='The role of the user in this study', max_length=32)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(help_text='The user that invited this collaborator to the study', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='study',
            name='collaborators',
        ),
        migrations.AddField(
            model_name='study',
            name='collaborators',
            field=models.ManyToManyField(help_text='Users working on this study', related_name='studies', through='studies.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studies.Study'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('collaborator', 'study')},
        ),
    ]
