# Generated by Django 2.2.13 on 2020-08-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("studies", "0020_add_collaborator_role")]

    operations = []
