# Generated by Django 2.2.13 on 2021-02-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0021_add_study_to_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='investigator_name',
            field=models.CharField(help_text='The name of the principle investigator of the study', max_length=200, null=True),
        ),
    ]
