# Generated by Django 2.2.13 on 2021-03-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0022_add_investigator_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'permissions': [('view_my_study', 'Can list studies that the user belongs to'), ('add_collaborator', 'Can add a collaborator to the study'), ('remove_collaborator', 'Can remove a collaborator to the study'), ('change_sequencing_status', 'Can update the sequencing status of a study'), ('change_ingestion_status', 'Can update the ingestion status of a study'), ('change_phenotype_status', 'Can update the phenotype status of a study'), ('subscribe_study', 'Can subscribe to a study for notifications'), ('subscribe_my_study', 'Can subscribe to a study that the user belongs to.'), ('unsubscribe_study', 'Can unsubscribe to a study for notifications'), ('unsubscribe_my_study', 'Can unsubscribe to a study that the user belongs to.')]},
        ),
    ]
