# Generated by Django 2.2.20 on 2021-05-07 16:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0023_add_subscription_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='additional_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
