# Generated by Django 2.2.24 on 2021-06-29 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0025_add_organizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time the study was created', null=True),
        ),
    ]
