# Generated by Django 2.2.24 on 2021-11-02 18:23

"""
This migration creates the domain attribute for the Study model and also
populates it using the spreadsheet found in this migrations folder.
"""

from django.db import migrations, models

import pandas as pd
import os

WRONG_DOMAIN = "CANCERBIRTHDEFECT"
CORRECT_DOMAIN = "CANCERANDBIRTHDEFECT"


def set_domain(apps, schema_editor):
    """
    Fix domain value for all Study objects
    """
    Study = apps.get_model("studies", "Study")

    studies = Study.objects.filter(domain=WRONG_DOMAIN).all()
    for study in studies:
        study.domain = CORRECT_DOMAIN
        study.save()


def undo_set_domain(apps, schema_editor):
    """
    Set domain to UNKNOWN for all Study objects.
    """
    Study = apps.get_model("studies", "Study")

    studies = Study.objects.filter(
        domain__in={CORRECT_DOMAIN, WRONG_DOMAIN}).all()
    for study in studies:
        study.domain = "UNKNOWN"
        study.save()


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0031_patch_dataservice'),
    ]

    operations = [
        migrations.RunPython(set_domain, reverse_code=undo_set_domain),
    ]
