# Generated by Django 2.2.24 on 2021-12-10 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0032_fix_populate_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='dewrangle_id',
            field=models.CharField(
                help_text='Unique identifier of the study in Dewrangle',
                blank=True, max_length=1024, null=True),
        ),
    ]
