from graph import Graph  # https://github.com/root-11/graph-theory
from kf_lib_data_ingest.validation.relations import RELATIONS as R

RULE_GRAPH = Graph()
RG = RULE_GRAPH

# Concepts
FAMILY = "FAMILY|ID"
PARTICIPANT = "PARTICIPANT|ID"
BIOSPECIMEN = "BIOSPECIMEN|ID"
ALIQUOT = "ALIQUOT|ID"
SEQUENCING_EXP = "SEQUENCING_EXPERIMENT|ID"
SOURCE_SEQ_FILE = "SOURCE_SEQUENCING_FILE|ID"
HARMONIZED_GENOMIC_FILE = "HARMONIZED_GENOMIC_FILE|ID"
ANALYTE = "ALIQUOT|ANALYTE"
GENDER = "PARTICIPANT|GENDER"
COMPOSITION = "BIOSPECIMEN|COMPOSITION"
TISSUE_TYPE = "BIOSPECIMEN|TISSUE_TYPE"
ANATOMY_SITE = "BIOSPECIMEN|ANATOMY_SITE"
LIBRARY_NAME = "SEQUENCING_EXPERIMENT|LIBRARY_NAME"
STRATEGY = "SEQUENCING_EXPERIMENT|STRATEGY"
PAIRED_END = "SEQUENCING_EXPERIMENT|PAIRED_END"
PLATFORM = "SEQUENCING_EXPERIMENT|PLATFORM"
INSTRUMENT = "SEQUENCING_EXPERIMENT|INSTRUMENT"
REFERENCE_GENOME = "SOURCE_SEQUENCING_FILE|REFERENCE_GENOME"

# ######### Hierarchy edges point --> upwards toward the concept root

# relationships between identifiers

RG.add_edge(PARTICIPANT, FAMILY, R.MANY_ANY)
RG.add_edge(BIOSPECIMEN, PARTICIPANT, R.MANY_ONE)
RG.add_edge(ALIQUOT, BIOSPECIMEN, R.MANY_ONE)
RG.add_edge(SOURCE_SEQ_FILE, SEQUENCING_EXP, R.MANY_ONE)
RG.add_edge(SOURCE_SEQ_FILE, ALIQUOT, R.MANY_ONE)

# participant optional attributes

RG.add_edge(GENDER, PARTICIPANT, R.ONEZERO_MANY)

# biospecimen required attributes

RG.add_edge(ANALYTE, ALIQUOT, R.ONE_MANY)

# biospecimen optional attributes

RG.add_edge(COMPOSITION, BIOSPECIMEN, R.ONEZERO_MANY)
RG.add_edge(TISSUE_TYPE, BIOSPECIMEN, R.ONEZERO_MANY)
RG.add_edge(ANATOMY_SITE, BIOSPECIMEN, R.ONEZERO_MANY)

# sequencing required attributes

RG.add_edge(LIBRARY_NAME, SEQUENCING_EXP, R.ONEZERO_ONE)
RG.add_edge(STRATEGY, SEQUENCING_EXP, R.ONE_MANY)
RG.add_edge(PAIRED_END, SEQUENCING_EXP, R.ONE_MANY)
RG.add_edge(PLATFORM, SEQUENCING_EXP, R.ONEZERO_MANY)
RG.add_edge(INSTRUMENT, SEQUENCING_EXP, R.ONEZERO_MANY)

# sequencing file required attributes
RG.add_edge(REFERENCE_GENOME, SOURCE_SEQ_FILE, R.ONE_MANY)
