# Generated by Django 2.2.13 on 2020-11-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(help_text='Time when the ingest_run was created')),
            ],
            options={
                'permissions': [('list_all_ingestrun', 'Show all ingest_runs')],
            },
        ),
    ]
