# Generated by Django 2.2.13 on 2021-03-30 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('ingest_runs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestrun',
            name='started_at',
            field=models.DateTimeField(help_text='Time when ingest process started running', null=True),
        ),
        migrations.AddField(
            model_name='ingestrun',
            name='stopped_at',
            field=models.DateTimeField(help_text='Time when ingest process stopped running', null=True),
        ),
        migrations.AlterField(
            model_name='ingestrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time when the ingest process was created', null=True),
        ),
        migrations.AlterField(
            model_name='ingestrun',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='The user who submitted this ingest process', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestruns', related_query_name='ingestrun', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ingestrun',
            name='input_hash',
            field=models.UUIDField(blank=True, editable=False, help_text='Identifies an ingest process execution by its input parameters. Autopopulated on save with the MD5 hash of all of the ingest process input parameters.', null=True),
        ),
        migrations.AlterField(
            model_name='ingestrun',
            name='job_log',
            field=models.OneToOneField(blank=True, help_text='The associated job log detailing the execution for this ingest process', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingestrun', related_query_name='ingestrun', to='jobs.JobLog'),
        ),
        migrations.AlterField(
            model_name='ingestrun',
            name='state',
            field=django_fsm.FSMField(default='not_started', help_text='The current state of the ingest process', max_length=50),
        ),
    ]
