# Generated by Django 2.2.20 on 2021-05-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest_runs', '0003_add_validation_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestrun',
            name='error_msg',
            field=models.TextField(blank=True, help_text='The error message that is a product of an ingest process failing. This field is populated in the exception handler before the fail method is called on the process.', null=True),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='error_msg',
            field=models.TextField(blank=True, help_text='The error message that is a product of an ingest process failing. This field is populated in the exception handler before the fail method is called on the process.', null=True),
        ),
    ]
