# Generated by Django 2.2.20 on 2021-05-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest_runs', '0003_add_validation_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestrun',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='Time when ingest process was lost modified', null=True),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='Time when ingest process was lost modified', null=True),
        ),
    ]
