# Generated by Django 2.2.20 on 2021-05-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest_runs', '0004_add_ingest_error_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestrun',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='Time when ingest process was last modified', null=True),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='Time when ingest process was last modified', null=True),
        ),
    ]
