name: Sentry Releases

on:
  push:
    tags:
      - "*.*.*"

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: prd
          set_commits: false
          version: ${{ github.ref }}
